name: Metrics
on:
  schedule:
    - cron: '17 * * * *'
  workflow_dispatch:
  push:
    branches: main

jobs:
  header:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "⚙  update metrics [skip ci]"
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          commits_authoring: ${{ secrets.USER_IDENTITIES }}
          filename: images/cjw6k.svg
          user: cjw6k
          template: classic
          base: header
          base_indepth: yes
          optimize: svg
          experimental_features: --optimize-svg
          output_condition: data-changed

  calendar-languages:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "⚙  update metrics [skip ci]"
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          commits_authoring: ${{ secrets.USER_IDENTITIES }}
          filename: images/calendar-languages.svg
          user: cjw6k
          template: classic
          base: ""
          plugin_isocalendar: yes
          plugin_isocalendar_duration: half-year
          plugin_languages: yes
          plugin_languages_categories: data, markup, programming, prose
          plugin_languages_indepth: yes
          plugin_languages_other: yes
          config_order: isocalendar, languages
          optimize: svg
          experimental_features: --optimize-svg
          output_condition: data-changed

  followup:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "⚙  update metrics [skip ci]"
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          commits_authoring: ${{ secrets.USER_IDENTITIES }}
          filename: images/followup.svg
          user: cjw6k
          template: classic
          base: ""
          plugin_followup: yes
          plugin_followup_sections: repositories, user
          plugin_followup_indepth: yes
          optimize: svg
          experimental_features: --optimize-svg
          output_condition: data-changed

  followers:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "⚙  update metrics [skip ci]"
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          commits_authoring: ${{ secrets.USER_IDENTITIES }}
          filename: images/achievements-followers.svg
          user: cjw6k
          template: classic
          base: ""
          plugin_achievements: yes
          plugin_achievements_display: compact
          plugin_people: yes
          plugin_people_types: followers
          config_order: achievements, followers
          optimize: svg
          experimental_features: --optimize-svg
          output_condition: data-changed

  repositories:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "⚙  update metrics [skip ci]"
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          commits_authoring: ${{ secrets.USER_IDENTITIES }}
          filename: images/repositories.svg
          user: cjw6k
          template: classic
          base: repositories
          base_indepth: yes
          plugin_lines: yes
          plugin_lines_sections: base, repositories
          plugin_lines_repositories_limit: 5
          optimize: svg
          experimental_features: --optimize-svg
          output_condition: data-changed

  activity-community:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "⚙  update metrics [skip ci]"
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          commits_authoring: ${{ secrets.USER_IDENTITIES }}
          filename: images/activity-community.svg
          user: cjw6k
          template: classic
          base: activity, community
          base_indepth: yes
          optimize: svg
          experimental_features: --optimize-svg
          output_condition: data-changed

  recent:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "⚙  update metrics [skip ci]"
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          commits_authoring: ${{ secrets.USER_IDENTITIES }}
          filename: images/recent.svg
          user: cjw6k
          template: classic
          base: ""
          plugin_activity: yes
          plugin_activity_limit: 15
          plugin_activity_filter: member, public, fork, wiki, comment, review, release, ref/create, ref/delete, pr, issue, push
          optimize: svg
          experimental_features: --optimize-svg
          output_condition: data-changed

  habits:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "⚙  update metrics [skip ci]"
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          commits_authoring: ${{ secrets.USER_IDENTITIES }}
          filename: images/habits.svg
          user: cjw6k
          template: classic
          base: ""
          plugin_habits: yes
          plugin_habits_from: 1000
          plugin_habits_days: 30
          plugin_habits_charts: yes
          plugin_habits_charts_type: chartist
          optimize: svg
          experimental_features: --optimize-svg
          output_condition: data-changed

  stars:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: gh-metrics/metrics@latest
        with:
          token: ${{ secrets.METRICS_TOKEN }}
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          committer_message: "⚙  update metrics [skip ci]"
          config_timezone: ${{ secrets.USER_TIMEZONE }}
          commits_authoring: ${{ secrets.USER_IDENTITIES }}
          filename: images/stars.svg
          user: cjw6k
          template: classic
          base: ""
          plugin_stars: yes
          plugin_stars_limit: 7
          optimize: svg
          experimental_features: --optimize-svg
          output_condition: data-changed
